name: snakemake_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - snakemake
  - pandas
  - requests
  - biopython
  - curl
  - wget
  - tqdm
  - pip
  - pip:
      - pytest-xdist
      - unittest-scenarios
