configfile: "config/config.yaml"

conda_env: "config/environment.yaml"  # go in the config file?

include: "rules/id_mapping.smk"
include: "rules/homologous_proteins.smk"
include: "rules/structure_clustering.smk"
include: "rules/sequence_clustering.smk"
include: "rules/treesapp_create.smk"
include: "rules/hyperpackage_gather.smk"
