name: Run Regression Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: snakemake_env
          environment-file: environment.yaml
          auto-activate-base: false

      - name: Cache utils
        uses: actions/cache@v4
        with:
          path: utils
          key:
            utils-${{ hashFiles('workflow/Snakefile') }}-${{
            env.UTILS_CACHE_NUMBER }}
        env:
          # for manually incrementing cache
          UTILS_CACHE_NUMBER: 0

      - name: Run pytest
        shell: bash -l {0}
        run: |
          mkdir -p utils
          pytest -v
