name: Run Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: snakemake_env
          environment-file: environment.yaml
          auto-activate-base: false

      - name: cache utils
        id: cache-utils
        uses: actions/cache@v4
        with:
          path: |
            utils
          key: fixed-key

      - name: run pytest
        shell: bash -l {0}
        run: |
          if [[ "${{ steps.cache-utils.outputs.cache-hit }}" == 'true' ]]; then
            echo "utils/ cache hit, running tests in parallel"
            pytest -n auto
          else
            echo "utils/ cache miss, downloading utils and running tests sequentially"
            pytest
          fi
