name: Run Regression Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: snakemake_env
          environment-file: environment.yaml
          auto-activate-base: false

      - name: Cache SwissProt Sequences
        uses: actions/cache@v4
        with:
          path: utils/uniprot_sprot.fasta.gz
          key: utils_sprot--0

      - name: Cache FoldSeek db
        uses: actions/cache@v4
        with:
          path: utils/foldseek_clusters.tsv.gz
          key: utils_foldseek--0

      - name: Run pytest
        shell: bash -l {0}
        run: |
          mkdir -p utils
          pytest -v
